---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: test
  image: ruby:2
  commands:
  - gem install nats
  - nats-pub -s tcp://nats:4222 greeting 'hello'
  - nats-pub -s tcp://nats:4222 greeting 'world'

services:
- name: nats
  image: nats:1.3.0
  ports:
  - 4222
  - 8222

...
