name: akuCommunity
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.1.0-dev+12

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # 瀑布流
  waterfall_flow: 2.0.2
  # 权限组件
  permission_handler: ^5.0.1+1
  # 版本信息
  package_info: 0.4.1
  #上拉加载
  pull_to_refresh: 1.6.2
  # 状态管理
  flutter_redux: ^0.5.3
  provider: ^4.1.3
  # 屏幕适配
  flutter_screenutil: ^3.2.0
  cupertino_icons: ^1.0.0
  # 打电话等各种功能
  url_launcher: 5.5.2
  # UI库
  flui: 0.9.2
  # 工具类
  flustars:
  common_utils:
  # icons
  flutter_icons: 1.1.0
  extended_image: 0.9.0
  extended_text: 4.1.0
  #轮播图
  flutter_swiper: ^1.1.6
  #路由
  fluro: ^1.6.3
  #滑动卡片
  font_awesome_flutter: ^8.8.1
  #图片预览
  photo_view: ^0.10.2
  #图片缓存
  cached_network_image: ^2.3.1
  #头像层叠
  image_stack: ^1.1.0
  #弹窗
  bot_toast: ^3.0.5
  #加载html
  flutter_html: ^1.0.2
  #上拉滑动
  sliding_up_panel: ^1.0.2
  #经纬度
  latlong: ^0.6.1
  #滑块
  flutter_slidable: ^0.5.7
  #http
  dio: ^3.0.10
  #骨架
  shimmer: ^1.1.2
  #时间选择
  flutter_datetime_picker: ^1.4.0
  #随机二维码
  qr_flutter: ^3.2.0
  #选择器
  flutter_picker: ^1.1.5
  #高德地图
  amap_map_fluttify:
  amap_location_fluttify: 0.18.0

  #用户存储路径
  path_provider: ^1.6.18

  fluwx: ^2.5.0+1
  get:
  velocity_x: ^1.3.1
  hive:
  hive_flutter:
  logger: ^0.9.4
  flutter_easyrefresh: ^2.1.8
  random_character:
    git:
      url: http://192.168.2.201:8099/zhangmeng/random_character.git

  image_picker: ^0.6.7+21
  power_logger:
    git:
      url: http://192.168.2.201:8099/aku_fe/power_logger.git
  flutter_rating_bar: ^3.2.0+1
  jpush_flutter: ^0.6.3
  badges: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  import_sorter: ^4.4.1
  flutter_asset_generator: ^0.6.1
  grinder:

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/tab/
    - assets/json/
    - assets/applications/
