name: akuCommunity
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.2+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # 瀑布流
  waterfall_flow: 2.0.2
  #
  extended_tabs: 0.2.3
  #
  flutter_anywhere_menus:
    git:
      url: https://github.com/haysuperman/flutter_anywhere_menus.git
      ref: eb91b16210fdac9907eaab9604c017d436e423ca
  # 权限组件
  permission_handler: ^5.0.1+1
  # 版本信息
  package_info: 0.4.1
  # toast提示
  oktoast: ^2.1.6
  #上拉加载
  pull_to_refresh: ^1.6.2
  # 状态管理
  flutter_redux: ^0.5.3
  provider: ^4.1.3
  # 屏幕适配
  flutter_screenutil: ^2.3.1
  cupertino_icons: ^0.1.3
  # 打电话等各种功能
  url_launcher: 5.5.2
  # UI库
  flui: 0.9.2
  # 工具类
  flustars: ^0.3.2
  # icons
  flutter_icons: 1.1.0
  extended_image: 0.9.0
  extended_text: 4.0.0
  # loading界面
  flutter_spinkit: ^3.1.0
  #轮播图
  flutter_swiper: ^1.1.6
  #路由
  fluro: ^1.6.3
  #滑动卡片
  font_awesome_flutter: ^8.8.1
  #弹窗
  flutter_beautiful_popup: ^1.5.0
  #图片预览
  photo_view: ^0.10.2
  #图片缓存
  cached_network_image: ^2.3.1
  flutter_luban: ^0.1.11
  #评价
  smooth_star_rating: ^1.1.1
  #头像层叠
  image_stack: ^1.1.0
  #弹窗
  bot_toast: ^3.0.4
  #加载html
  flutter_html: ^1.0.2
  #图片多选
  multi_image_picker: ^4.7.13
  #上拉滑动
  sliding_up_panel: ^1.0.2
  #经纬度
  latlong: ^0.6.1
  #谷歌地图
  flutter_map: ^0.10.1+1
  #滑块
  flutter_slidable: ^0.5.7
  #动画效果
  flare_flutter: ^2.0.6
  #http
  dio: ^3.0.10
  #骨架
  shimmer: ^1.1.1
  #动画库
  animate_do: ^1.7.3
  #动画alert
  rflutter_alert: ^1.1.0
  #扫码
  barcode_scan: ^3.0.1
  #时间选择
  flutter_datetime_picker: ^1.4.0
  #随机二维码
  qr_flutter: ^3.2.0
  #选择器
  flutter_picker: ^1.1.5
  #加载动画
  loading_animations: ^2.1.0
  #读取pdf
  flutter_pdfview: ^1.0.3+5
  #用户存储路径
  path_provider: ^1.6.18
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

  # 路由管理
  ff_annotation_route: 3.3.2

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/example/
    - assets/tab/
    - assets/json/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
