name: akuCommunity
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.1.10-dev+17

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # 权限组件
  permission_handler: ^6.1.1
  # 版本信息
  package_info: ^2.0.0
  provider: ^5.0.0
  # 屏幕适配
  flutter_screenutil: ^5.0.0-nullsafety.11
  cupertino_icons: ^1.0.2
  # 打电话等各种功能
  url_launcher: ^6.0.2
  # 工具类
  flustars: ^2.0.1
  # icons
  # TODO need remove
  flutter_icons: 1.1.0
  extended_text: ^5.0.4
  #图片预览
  photo_view: ^0.11.1
  #图片缓存
  cached_network_image: ^3.0.0-nullsafety
  #弹窗
  bot_toast: ^4.0.1
  #TODO need remove
  #上拉滑动
  sliding_up_panel: ^1.0.2
  #滑块
  flutter_slidable: ^0.6.0-nullsafety.0
  #http
  dio: ^4.0.0-prev3
  #骨架
  shimmer: ^2.0.0-nullsafety.0
  #随机二维码
  qr_flutter: ^4.0.0

  #用户存储路径
  path_provider: ^2.0.1

  fluwx: ^3.3.0
  get: ^4.0.0-nullsafety.2
  velocity_x: ^2.6.0
  hive: ^2.0.0
  hive_flutter: ^1.0.0
  logger: ^1.0.0
  flutter_easyrefresh: ^2.1.8
  random_character:
    git:
      url: http://159.75.73.143:8080/mengfucius/random_character
      ref: null-safety

  image_picker: ^0.7.3
  power_logger: ^1.0.0-nullsafety.0
  flutter_rating_bar: ^4.0.0
  jpush_flutter: ^2.0.1

  badges: ^2.0.0-nullsafety.1
  amap_flutter_map:
    git:
      url: http://159.75.73.143:8080/third_packages/amap_flutter_map
      ref: nullsafety
  amap_flutter_location: ^1.0.1
  amap_flutter_base: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  import_sorter: ^4.4.2
  grinder: ^0.9.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/tab/
    - assets/json/
    - assets/applications/
    - assets/static/

import_sorter:
  emojis: true
  comments: false
