name: aku_community
description: A new Flutter project.
publish_to: "none"

version: 1.3.0-dev+38

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  permission_handler: ^7.1.0
  package_info: ^2.0.0
  provider: ^5.0.0
  flutter_screenutil: ^5.0.0+2
  cupertino_icons: ^1.0.3
  url_launcher: ^6.0.3
  flustars: ^2.0.1
  flutter_icons:
    git:
      url: git@git.oa00.com:flutter_third/flutter-icons.git
  #弹窗
  bot_toast: ^4.0.1
  #滑块
  flutter_slidable: ^0.6.0
  #http
  dio: ^4.0.0
  #骨架
  shimmer: ^2.0.0
  #随机二维码
  qr_flutter: ^4.0.0

  #用户存储路径
  path_provider: ^2.0.1

  fluwx: ^3.4.2
  get: ^4.1.4
  velocity_x: ^3.0.0
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  logger: ^1.0.0
  flutter_easyrefresh: ^2.2.1
  random_character:
    git:
      url: git@git.oa00.com:flutter_pub/random_character.git
      ref: null-safety

  image_picker: ^0.7.4
  power_logger: ^1.2.1
  flutter_rating_bar: ^4.0.0
  jpush_flutter:
    git:
      url: https://git.oa00.com/flutter_third/jpush-flutter-plugin
  open_file: ^3.2.1
  badges: ^2.0.0-nullsafety.1
  amap_flutter_map: ^2.0.1
  amap_flutter_location: ^2.0.0
  amap_flutter_base: ^2.0.0
  animated_text_kit: ^4.2.1
  firebase_core: ^1.1.1
  firebase_crashlytics: ^2.0.3
  share: ^2.0.1
  collection: ^1.15.0
  json_annotation: ^4.0.1
  waterfall_flow: ^3.0.1
  qr_code_scanner: ^0.4.0
  equatable: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  import_sorter: ^4.5.1
  grinder: ^0.9.0
  flutter_native_splash: ^1.1.8+4
  json_serializable: ^4.1.1
  build_runner: ^2.0.2
  yaml: ^3.1.0
  pub_semver: ^2.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/tab/
    - assets/applications/
    - assets/static/

import_sorter:
  emojis: true
  comments: false
  ignored_files:
    - \*\/generated_plugin_registrant.dart
