name: akuCommunity
description: A new Flutter project.
publish_to: "none"

version: 1.1.21-dev+27

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  permission_handler: ^6.1.1
  package_info: ^2.0.0
  provider: ^5.0.0
  flutter_screenutil: ^5.0.0-nullsafety.11
  cupertino_icons: ^1.0.2
  url_launcher: ^6.0.2
  flustars: ^2.0.1
  # icons
  # TODO need remove
  flutter_icons: 1.1.0
  #弹窗
  bot_toast: ^4.0.1
  #滑块
  flutter_slidable: ^0.6.0-nullsafety.0
  #http
  dio: ^4.0.0
  #骨架
  shimmer: ^2.0.0-nullsafety.0
  #随机二维码
  qr_flutter: ^4.0.0

  #用户存储路径
  path_provider: ^2.0.1

  fluwx: ^3.3.0
  get: ^4.0.0-nullsafety.2
  velocity_x: ^2.6.0
  hive: ^2.0.3
  hive_flutter: ^1.0.0
  logger: ^1.0.0
  flutter_easyrefresh: ^2.2.1
  random_character:
    git:
      url: http://159.75.73.143:8080/mengfucius/random_character
      ref: null-safety

  image_picker: ^0.7.3
  power_logger: ^1.1.1-nullsafety.3
  flutter_rating_bar: ^4.0.0
  jpush_flutter: ^2.0.1
  open_file: ^3.1.0
  badges: ^2.0.0-nullsafety.1
  amap_flutter_map:
    git:
      url: http://159.75.73.143:8080/third_packages/amap_flutter_map
      ref: nullsafety
  amap_flutter_location: ^1.0.1
  amap_flutter_base: ^1.0.2
  animated_text_kit: ^4.1.1
  firebase_core: ^1.0.3
  firebase_crashlytics: ^2.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  import_sorter: ^4.4.2
  grinder: ^0.9.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/tab/
    - assets/applications/
    - assets/static/

import_sorter:
  emojis: true
  comments: false
